name: Java CI mit Gradle

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v7

      - name: Java JDK einrichten
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle validieren (Sicherheit)
        uses: gradle/actions/wrapper-validation@v4

      - name: Build mit Gradle ausführen
        uses: gradle/actions/setup-gradle@v4
        with:
          arguments: build
